(()=>{let renderer,scene,camera,raycaster,mouse;const targets=[],look=new THREE.Vector3(0,0,0),keys={};let dragging=false,lastX=0,lastY=0,hovered=null,zoom=30;const stage=()=>document.getElementById("cityStage"),hint=()=>document.getElementById("buildingHint");
function mat(c,rough=.8,metal=0){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal})}
function box(g,p,c){const m=new THREE.Mesh(new THREE.BoxGeometry(...g),mat(c));m.position.set(...p);m.castShadow=m.receiveShadow=true;return m}
function roof(p,w,d,c){const m=new THREE.Mesh(new THREE.ConeGeometry(Math.max(w,d)*.72,.9,4),mat(c));m.rotation.y=Math.PI/4;m.position.set(...p);m.scale.set(w/Math.max(w,d),1,d/Math.max(w,d));m.castShadow=true;return m}
function building(name,action,x,z,w,h,d,c,accent){const g=new THREE.Group();g.position.set(x,0,z);g.userData={action,name};g.add(box([w,.5,d],[0,.25,0],0x283238));g.add(box([w,h,d],[0,h/2+.5,0],c));g.add(roof([0,h+1,z*0?0:0],w,d,accent));for(let yy=1.5;yy<h;yy+=1.35){for(let xx=-w/2+1;xx<w/2;xx+=1.35){g.add(box([.45,.55,.06],[xx,yy,d/2+.035],0x91b7c0))}}const sign=box([Math.min(w*.72,6),.65,.12],[0,h*.52+.5,d/2+.08],accent);g.add(sign);g.userData.hit=sign;targets.push(g);scene.add(g);return g}
function tree(x,z){const g=new THREE.Group();g.add(box([.35,1.8,.35],[0,.9,0],0x5a4030));const l=new THREE.Mesh(new THREE.DodecahedronGeometry(1.15),mat(0x285b3a));l.position.y=2.1;l.castShadow=true;g.add(l);g.position.set(x,0,z);scene.add(g)}
function car(x,z,r){const g=new THREE.Group();g.position.set(x,.38,z);g.rotation.y=r;g.add(box([2.5,.55,1.2],[0,0,0],0x8d9aa0));g.add(box([1.25,.45,1.0],[0,.45,0],0x344b55));for(const sx of[-.85,.85])for(const sz of[-.55,.55]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.22,.22,.18,12),mat(0x101419));w.rotation.z=Math.PI/2;w.position.set(sx,-.25,sz);g.add(w)}scene.add(g)}
function road(x,z,w,d,r=0){const m=box([w,.12,d],[x,.02,z],0x242b30);m.rotation.y=r;scene.add(m);const line=box([w*.92,.025,.12],[x,.09,z],0xd2bd61);line.rotation.y=r;scene.add(line)}
function init(){const c=document.getElementById("city3d");scene=new THREE.Scene();scene.background=new THREE.Color(0x78a8b8);scene.fog=new THREE.Fog(0x78a8b8,42,105);camera=new THREE.PerspectiveCamera(48,c.clientWidth/c.clientHeight,.1,180);camera.position.set(0,24,27);camera.lookAt(look);renderer=new THREE.WebGLRenderer({canvas:c,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(c.clientWidth,c.clientHeight,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();
scene.add(new THREE.HemisphereLight(0xc9e9ff,0x23301f,2.1));const sun=new THREE.DirectionalLight(0xffe0a1,3.2);sun.position.set(-25,45,20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const ground=box([110,.35,90],[0,-.2,0],0x667653);scene.add(ground);road(0,0,110,8);road(0,-16,110,7);road(0,16,110,7);road(-28,0,7,90);road(0,0,7,90);road(28,0,7,90);
building("مركز المهمات","missions",-18,-12,9,8,7,0x254d67,0xd6aa43);building("مركز التدريب","training",-3,-12,8,7,7,0x315c4c,0x75cfa0);building("مركز التسوق","market",17,-10,10,9,8,0x614b2d,0xe3bd61);building("سوق التجارة","trade",-19,13,10,8,8,0x3f4d65,0x86b7d2);building("مقر العصابة","base",2,13,12,11,9,0x482f39,0xc46b63);building("ملفي","profile",21,12,8,6,7,0x4b5a62,0xb0c7cf);
building("برج المدينة","none",0,30,8,19,8,0x344650,0x9ab6bf);building("مركز الخدمات","none",-36,-23,9,10,8,0x3e5360,0x8eb3c4);
for(const [x,z] of[[-43,-12],[-39,7],[-34,22],[-25,27],[-10,29],[10,28],[34,22],[39,5],[38,-17],[25,-25],[10,-27],[-8,-25]])tree(x,z);
for(const [x,z,r] of[[-30,0,0],[12,0,0],[31,0,0],[-7,-20,0],[7,20,Math.PI],[-12,20,Math.PI]])car(x,z,r);
events(c);animate()}
function resize(){if(!renderer)return;const c=document.getElementById("city3d");camera.aspect=c.clientWidth/c.clientHeight;camera.updateProjectionMatrix();renderer.setSize(c.clientWidth,c.clientHeight,false)}
function clamp(){look.x=Math.max(-40,Math.min(40,look.x));look.z=Math.max(-34,Math.min(34,look.z))}
function applyCamera(){const a=camera.position.clone().sub(look);a.y=zoom*.72;const horiz=Math.sqrt(a.x*a.x+a.z*a.z)||1;const scale=zoom/horiz;a.x*=scale;a.z*=scale;camera.position.copy(look).add(a);camera.lookAt(look)}
function events(c){c.addEventListener("pointerdown",e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;c.setPointerCapture(e.pointerId)});c.addEventListener("pointermove",e=>{const r=c.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;if(dragging){look.x-=(e.clientX-lastX)*.035;look.z+=(e.clientY-lastY)*.035;clamp();applyCamera()}lastX=e.clientX;lastY=e.clientY;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(targets,true);const g=hits.length?hits[0].object.parent:null;let root=g;while(root&&root.parent!==scene)root=root.parent;if(root&&root.userData.name){hovered=root;hint().textContent=root.userData.name+" — اضغط للدخول";hint().classList.add("show")}else{hovered=null;hint().classList.remove("show")}});c.addEventListener("pointerup",e=>{if(!dragging)return;dragging=false;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(targets,true);if(hits.length){let g=hits[0].object;while(g&&(!g.userData||!g.userData.action))g=g.parent;if(g&&g.userData.action&&g.userData.action!=="none"&&typeof act==="function")act(g.userData.action)}});c.addEventListener("wheel",e=>{zoom+=e.deltaY*.018;zoom=Math.max(18,Math.min(43,zoom));applyCamera();e.preventDefault()},{passive:false});c.addEventListener("contextmenu",e=>e.preventDefault());window.addEventListener("resize",resize)}
function animate(){requestAnimationFrame(animate);if(!renderer)return;for(const g of targets){if(g.userData.action){g.rotation.y=Math.sin(performance.now()*.0004+g.position.x)*.002}}renderer.render(scene,camera)}
window.addEventListener("load",init);
})();