class LocationScene extends Phaser.Scene{
  constructor(){super('LocationScene');}
  init(d){this.city=d.city||'main';this.kind=d.kind;this.title=d.name;}
  create(){var s=this,gs=window.gameState;header(this,this.title,'home');button(this,24,128,120,34,'← رجوع',COLORS.panel2,function(){s.scene.start('CityScene',{city:s.city});});
    if(this.kind==='shop')this.shop();else if(this.kind==='training')this.scene.start('TrainingScene');else if(this.kind==='blackmarket')this.market();else if(this.kind==='airport')this.airport();else if(this.kind==='arena')this.arena();else if(this.kind==='hospital')this.hospital();else if(this.kind==='prison')this.prison();else this.locked();
  }
  shop(){var s=this,items=CITY_PRODUCTS[this.city]||CITY_PRODUCTS.main;txt(s,400,178,'منتجات '+CITIES[this.city].name,18,COLORS.muted);items.forEach(function(p,i){var x=55+(i%2)*360,y=210+Math.floor(i/2)*120;panel(s,x,y,330,100,COLORS.panel2);txt(s,x+30,y+34,p.icon,28);txt(s,x+78,y+28,p.name,16,COLORS.text,0);txt(s,x+78,y+56,p.price+' 💵',13,COLORS.gold,0);button(s,x+215,y+55,95,28,'شراء',COLORS.gold,function(){if(gs.resources.cash>=p.price){gs.resources.cash-=p.price;gs.addLog('اشتريت '+p.name);gs.save();s.scene.restart();}else txt(s,400,500,'المال غير كافٍ',14,COLORS.red);});});}
  market(){var s=this;txt(s,400,178,'السوق السوداء',22,COLORS.gold);txt(s,400,208,'طلبات ومهمات لاعبين: مال • سمعة • نقاط تحمل',14,COLORS.muted);MISSIONS.forEach(function(m,i){var y=238+i*70;panel(s,65,y,670,58,COLORS.panel2);txt(s,85,y+16,m.name,15,COLORS.text,0);txt(s,270,y+16,m.type+' • '+m.difficulty,12,COLORS.muted,0);txt(s,470,y+16,m.reward+' 💵 + '+m.xp+' XP',12,COLORS.gold,0);button(s,635,y+12,82,32,'عرض',COLORS.gold,function(){s.scene.start('MissionsScene');});});}
  airport(){var s=this,from=CITIES[this.city].name;txt(s,400,178,'لوحة الرحلات',20,COLORS.gold);var cities=Object.keys(CITIES).filter(function(k){return !k.startsWith('future')&&k!==s.city;});cities.forEach(function(k,i){var y=220+i*58;panel(s,70,y,660,48,COLORS.panel2);txt(s,90,y+13,CITIES[k].emoji+' '+CITIES[k].name,14,COLORS.text,0);txt(s,360,y+13,'من '+from,12,COLORS.muted,0);txt(s,520,y+13,(180+i*90)+' 💵  •  '+(12+i*3)+' دقيقة',12,COLORS.gold,0);button(s,650,y+8,65,32,'سافر',COLORS.blue,function(){if(gs.resources.cash>=(180+i*90)){gs.resources.cash-=(180+i*90);gs.travel(k);s.scene.start('CityScene',{city:k});}});});}
  arena(){var s=this,enemy=gs.startArena();txt(s,400,178,'الحلبة',24,COLORS.gold);txt(s,400,212,'كل انتصار يفتح خصمًا أقوى.',14,COLORS.muted);panel(s,170,250,460,170,COLORS.panel2);txt(s,400,292,'الخصم',16,COLORS.muted);txt(s,400,330,enemy.name,24,COLORS.text);txt(s,400,365,'قوة '+enemy.power,16,COLORS.red);button(s,250,390,300,38,'دخول المواجهة',COLORS.red,function(){window.pendingArena=enemy;s.scene.start('ArenaBattleScene');});}
  hospital(){emptyState(this,190,'🏥 المستشفى','المقاتل هنا يتلقى العلاج بعد الهزيمة.');}
  prison(){emptyState(this,190,'🔒 السجن','هنا يظهر اللاعب عند فشل المهمة والقبض عليه.');}
  locked(){emptyState(this,190,this.title,this.title.indexOf('العالم')>=0?'قريبًا':'غير متاح الآن');}
}