class LocationScene extends Phaser.Scene{
constructor(){super('LocationScene');}
init(d){this.city=d.city||'main';this.kind=d.kind;this.title=d.name;this.status=d.status;}
create(){var s=this;header(s,this.title,'home');button(s,24,122,120,32,'← رجوع',COLORS.panel2,()=>s.scene.start('CityScene',{city:s.city}));
if(this.kind==='shop')this.shop();else if(this.kind==='training')s.scene.start('TrainingScene');else if(this.kind==='blackmarket')this.market();else if(this.kind==='airport')this.airport();else if(this.kind==='arena')this.arena();else if(this.kind==='hospital')this.hospital();else if(this.kind==='prison')this.prison();else if(this.kind==='profile')this.profile();else if(this.kind==='map')this.map();else this.locked();}
shop(){var s=this,items=CITY_PRODUCTS[this.city]||CITY_PRODUCTS.main;txt(s,400,174,'متجر '+CITIES[this.city].name,21,COLORS.gold);txt(s,400,202,'منتجات مختلفة حسب المدينة — للتجارة أو الاستخدام داخل اللعبة',12,COLORS.muted);items.forEach((p,i)=>{var x=45+(i%2)*365,y=230+Math.floor(i/2)*118;panel(s,x,y,340,100,COLORS.panel2);txt(s,x+28,y+25,p.icon,27);txt(s,x+72,y+22,p.name,15,COLORS.text,0);txt(s,x+72,y+52,fmt(p.price)+' 💵',13,COLORS.gold,0);button(s,x+220,y+55,95,28,'شراء',COLORS.gold,()=>{if(window.gameState.resources.cash>=p.price){window.gameState.resources.cash-=p.price;window.gameState.addLog('شراء '+p.name);window.gameState.save();s.scene.restart();}});});}
market(){var s=this;txt(s,400,174,'السوق السوداء',22,COLORS.gold);txt(s,400,202,'مهمات عامة وخاصة وطلبات اللاعبين مقابل المال والسمعة ونقاط التحمل',12,COLORS.muted);MISSIONS.forEach((m,i)=>{var y=232+i*72;panel(s,48,y,704,60,COLORS.panel2);txt(s,68,y+13,m.name,14,COLORS.text,0);txt(s,255,y+13,m.type+' • '+m.difficulty,11,COLORS.muted,0);txt(s,445,y+13,'💵 '+fmt(m.reward)+'  XP '+m.xp,11,COLORS.gold,0);button(s,650,y+10,82,32,'عرض',COLORS.gold,()=>s.scene.start('MissionsScene'));});}
airport(){var s=this,gs=window.gameState,from=gs.lastCity&&CITIES[gs.lastCity]?CITIES[gs.lastCity].name:CITIES[this.city].name;txt(s,400,174,'لوحة الرحلات',21,COLORS.gold);txt(s,400,202,'الوجهة • السعر • الوقت',12,COLORS.muted);var keys=Object.keys(CITIES).filter(k=>k!=='main'&&k!==this.city);keys.forEach((k,i)=>{var y=232+i*55;panel(s,48,y,704,46,COLORS.panel2);txt(s,68,y+11,CITIES[k].emoji+' '+CITIES[k].name,13,COLORS.text,0);txt(s,300,y+11,'من '+from,11,COLORS.muted,0);txt(s,455,y+11,(180+i*90)+' 💵  •  '+(12+i*3)+' دقيقة',11,COLORS.gold,0);button(s,660,y+7,72,32,'سافر',COLORS.blue,()=>{var price=180+i*90;if(gs.resources.cash>=price){gs.resources.cash-=price;gs.travel(k);s.scene.start('CityScene',{city:k});}});});}
arena(){var s=this,gs=window.gameState,e=gs.startArena();txt(s,400,174,'الحلبة',23,COLORS.gold);txt(s,400,202,'كل خصم مهزوم يُستبدل بمقاتل أقوى.',12,COLORS.muted);panel(s,155,235,490,180,COLORS.panel2);txt(s,400,273,'المقاتل القادم',14,COLORS.muted);txt(s,400,310,e.name,25,COLORS.text);txt(s,400,350,'قوة '+e.power,15,COLORS.red);button(s,245,375,310,38,'ابدأ المواجهة',COLORS.red,()=>{window.pendingArena=e;s.scene.start('ArenaBattleScene');});}
hospital(){emptyState(this,205,'🏥 المستشفى','شخصية اللاعب راقدة وتتلقى العلاج بعد الهزيمة.');}
prison(){emptyState(this,205,'🔒 السجن','شخصية اللاعب خلف الزنزانة بعد فشل المهمة والقبض عليه.');}
profile(){var gs=window.gameState;panel(this,70,185,660,300,COLORS.panel2);txt(this,400,220,'ملف العصابة',25,COLORS.gold);txt(this,400,270,'المستوى '+gs.progress.level+'  •  XP '+gs.progress.xp+' / '+gs.progress.nextXp,15,COLORS.text);txt(this,400,310,'💵 '+fmt(gs.resources.cash)+'   🎖️ '+fmt(gs.resources.reputation)+'   🏋️ '+gs.progress.stamina,14,COLORS.muted);txt(this,400,360,'قوة '+gs.stats.strength+'   سرعة '+gs.stats.speed,14,COLORS.text);txt(this,400,400,'دفاع '+gs.stats.defense+'   دقة '+gs.stats.accuracy,14,COLORS.text);}
map(){var s=this;txt(s,400,174,'خريطة العالم',22,COLORS.gold);var keys=['cairo','riyadh','dubai','paris','shanghai'];keys.forEach((k,i)=>{var x=70+(i%3)*240,y=220+Math.floor(i/3)*110;panel(s,x,y,210,82,CITIES[k].color);txt(s,x+105,y+20,CITIES[k].emoji+' '+CITIES[k].name,16,'#fff');button(s,x+35,y+47,140,25,'دخول المدينة',COLORS.panel2,()=>{window.gameState.travel(k);s.scene.start('CityScene',{city:k});});});}
locked(){emptyState(this,205,this.title,this.status||'غير متاح الآن');}
}